Please review the different types of multiplications here: https://www.tutorialexample.com/understand-numpy-np-multiply-np-dot-and-operation-a-beginner-guide-numpy-tutorial/ 

Source for np.einsum tutorial : https://ajcr.net/Basic-guide-to-einsum/

In [1]:
import numpy as np

In [3]:
A = np.array([0,1,2])
B = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])

In [4]:
A*B

ValueError: operands could not be broadcast together with shapes (3,) (3,4) 

In [5]:
# Need to transpose A to be olumn vector to be able to do hHadamard product as: 0 * first row, 1 * second row, 2 * third row. Then we would also like to sum along the columns (sum each row together)

In [7]:
(A[:,np.newaxis]*B).sum(axis=1)

array([ 0, 22, 76])

In [8]:
# This works fine but is prone to errors and can be done better wit np.einsum()
np.einsum('i,ij->i', A, B)

array([ 0, 22, 76])

Why better? In short because we didn’t need to reshape A at all and, most importantly, the multiplication didn’t create a temporary array like A[:, np.newaxis] * B did. Instead, einsum simply summed the products along the rows as it went. Even for this tiny example, I timed einsum to be about three times faster.

In [23]:
# Example
s_tc = np.array([[1,0,0],[1,2,0], [1,2,3]])
km_t = np.array([0.1,0.2,0.3])

In [24]:
s_tc * km_t # Here each cohort is multiplied with each time, which is not the desiered way of multiplication

array([[0.1, 0. , 0. ],
       [0.1, 0.4, 0. ],
       [0.1, 0.4, 0.9]])

In [25]:
km_t  * s_tc # same outcome as before

array([[0.1, 0. , 0. ],
       [0.1, 0.4, 0. ],
       [0.1, 0.4, 0.9]])

In [27]:
# If we want the matrix by cohort we just need to add index
np.einsum('tc,t->tc', s_tc, km_t)

array([[0.1, 0. , 0. ],
       [0.2, 0.4, 0. ],
       [0.3, 0.6, 0.9]])

In [26]:
# To have the sum just specify that you want t as an output instead of tc
np.einsum('tc,t->t', s_tc, km_t)

array([0.1, 0.6, 1.8])

In [28]:
# No problem to have it the other way arround:
np.einsum('t,tc->tc', km_t, s_tc)

array([[0.1, 0. , 0. ],
       [0.2, 0.4, 0. ],
       [0.3, 0.6, 0.9]])